name: Rust CI/CD

on:
  push:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v6
    - uses: dtolnay/rust-toolchain@stable
      with:
        targets: x86_64-pc-windows-msvc , i686-pc-windows-msvc

    - uses: Swatinem/rust-cache@v2
      
    - name: Build x86-64
      run: cargo build --release --verbose
      
    - name: Build x86
      run: cargo build --release --target i686-pc-windows-msvc --verbose

    - uses: negrutiu/nsis-install@v2
    - uses: hustcer/setup-nu@v3
      with:
        version: "0.113"

    - name: Build installer
      shell: nu {0}
      run: makensis /V4 /WX $"/DVERSION=(open Cargo.toml | get package.version)" installer.nsi

    - uses: actions/upload-artifact@v6
      with:
        name: uo_keyboard
        path: uo_keyboard_setup.exe
        compression-level: 0
        if-no-files-found: error

  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v6    
    - uses: actions/download-artifact@v7
      with:
        path: artifacts
    
    - name: Display structure
      run: ls -R artifacts
    
    - name: Re-Tag preview
      run: gh release delete preview --yes || true
      env:
        GH_TOKEN: ${{ github.token }}

    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: preview
        name: Ũõ Keyboard Preview
        draft: false
        prerelease: true
        files: artifacts/**/*
        